jobs:
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Run the Maven test task
        run: ./mvnw clean test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Run the Maven build
        run: ./mvnw clean package

on:
  push:
    branches:
      - main
      - master
  pull_request: